import type { InsertProject } from "../schema";

export const PROJECT_SEEDS: InsertProject[] = [
  {
    title: "Clean Water for Abuja Communities",
    description: "Borehole drilling, water purification systems, and sanitation infrastructure serving rural communities around Abuja.",
    status: "ongoing",
    country: "Nigeria",
    category: "Clean Water",
    goalAmount: 150000,
    raisedAmount: 92000,
    imageUrl: "/abuja-water.png",
    location: "Abuja",
    beneficiaries: 4200,
  },
  {
    title: "Education Access and School Renewal",
    description: "School construction, teacher training, scholarship support, and learning material distribution for underserved communities.",
    status: "ongoing",
    country: "Nigeria",
    category: "Education",
    goalAmount: 200000,
    raisedAmount: 128500,
    imageUrl: "/sectors/construction.png",
    location: "Kano",
    beneficiaries: 3100,
  },
  {
    title: "Rural Health Outreach",
    description: "Rural clinics, mobile medical teams, maternal health support, and disease prevention campaigns.",
    status: "completed",
    country: "Ghana",
    category: "Healthcare",
    goalAmount: 85000,
    raisedAmount: 85000,
    imageUrl: "/sectors/finance.png",
    location: "Tamale",
    beneficiaries: 1800,
  },
  {
    title: "Solar Energy for Community Infrastructure",
    description: "Solar panel installation, mini-grid projects, and off-grid electrification in rural areas.",
    status: "upcoming",
    country: "Kenya",
    category: "Clean Energy",
    goalAmount: 175000,
    raisedAmount: 42000,
    imageUrl: "/sectors/transport.png",
    location: "Kisumu",
    beneficiaries: 2500,
  },
  {
    title: "Women Empowerment Market Hub",
    description: "Business training, microfinance access, leadership programs, and mentorship for African women.",
    status: "ongoing",
    country: "Rwanda",
    category: "Community Development",
    goalAmount: 95000,
    raisedAmount: 61000,
    imageUrl: "/sectors/retail.png",
    location: "Kigali",
    beneficiaries: 900,
  },
];
